### ISSUE TITLE
Bower package is not in sync with the latest changes

### ISSUE THREAD

**Issue by csksm** [brianchance/knockout-x-editable#28]

**Comment by csksm** [comment]
Hi @brianchance, could you please publish release v0.1.2 so that Bower package could pick up the latest changes? Thanks.

**Comment by brianchance** [comment]
I think I got it done, had to add a tag. Bower should pick that up?

**Comment by csksm** [comment]
Yes, Bower already picked up v0.1.2. Thanks!
