### ISSUE TITLE
Text area with WSYWIG editors?

### ISSUE THREAD

**Issue by ewassef** [brianchance/knockout-x-editable#29]
More of a question than an issue
Wondering if there is a way to bind to a text area but have that textarea show up with an editor instead of just the HTML element

**Comment by brianchance** [comment]
What type of editor?

**Comment by ewassef** [comment]
no single one in particular, most of the plugins get called on a textarea and allow the user to enter html etc. is there one thats compatible?

**Comment by brianchance** [comment]
I am sure there are. Have not looked.

**Comment by ewassef** [comment]
to add more context, you usually call the editor on the text area as a jquery plugin (or via an attribute) (( $("selector").editor())) So, im wondering if we can do this for the editing of textareas even though there is no visible element

**Comment by ewassef** [comment]
This is the one i like to use http://waxolunist.github.io/bootstrap3-wysihtml5-bower/

**Comment by brianchance** [comment]
I am sure it is possible with x-editable and with knockout, but not sure
this plugin will do it.

**Comment by ewassef** [comment]
any ideas or suggestions on how to accomplish this?

**Comment by brianchance** [comment]
Really have not worked with this in while, sorry.
